name: Data Ingestion

on:
  schedule:
    - cron: "*/30 * * * *"   # adjust as you like
  workflow_dispatch:         # manual trigger

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure GCP credentials
        env:
          KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }}
        run: |
          echo "$KEY_JSON" > sa.json
          export GOOGLE_APPLICATION_CREDENTIALS="$PWD/sa.json"
          gcloud auth activate-service-account --key-file=sa.json
          gcloud config set project ${{ secrets.GCP_PROJECT }}

      - name: Run data pull
        run: |
          python scripts/data_pull.py
